# Generated by Django 2.2.7 on 2019-11-21 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20191120_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodscategoryprice',
            options={'verbose_name': '商品类别价格', 'verbose_name_plural': '商品类别价格'},
        ),
    ]
