# Generated by Django 2.2.7 on 2019-12-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderinfo',
            options={'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='goods_num',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='nums',
            field=models.IntegerField(default=0, verbose_name='购买数量'),
        ),
    ]
