# Generated by Django 2.2.7 on 2019-12-09 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20191209_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='singer_name',
            new_name='signer_name',
        ),
    ]
