"""
Django settings for muke project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""
import datetime
import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, BASE_DIR)
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))
sys.path.insert(0, os.path.join(BASE_DIR, 'extra_apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '-dyrnn=4-2b5aza!b&n3a(=lnq-z&dc73$*5h$o6=6%2-f+#4y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# 替换系统用户

AUTH_USER_MODEL = 'users.UserProfile'

# Application definition

INSTALLED_APPS = [
    'simpleui',
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',  # 过滤
    'corsheaders',  # 跨域
    'DjangoUeditor',  # 富文本
    'import_export',  # 数据导出
    'users.apps.UsersConfig',
    'goods.apps.GoodsConfig',
    'trade.apps.TradeConfig',
    'user_operation.apps.UserOperationConfig',
    'rest_framework.authtoken',  # drf 的 token登录
    'social_django',  # 第三方登录插件

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.common.CommonMiddleware',
]
CORS_ORIGIN_ALLOW_ALL = True
ROOT_URLCONF = 'muke.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'muke.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mxshop',
        'USER': 'root',  # 用户名
        'HOST': '127.0.0.1',  # IP
        'PASSWORD': 'root',  # 密码
        # 'HOST': '47.98.34.221',  # IP
        'POST': '3306',  # 端口
        'CHARSET': 'UTF-8'
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False  # 时间utc时间，本地时间改为False

DEBUG = True

# 身份验证后端 修改了登录时候验证的后端
AUTHENTICATION_BACKENDS = (
    'users.views.CutomBackend',
    'social_core.backends.weibo.WeiboOAuth2',
    'social_core.backends.qq.QQOAuth2',
    'social_core.backends.weixin.WeixinOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

# jwt配置
JWT_AUTH = {
    'JWT_EXPIRATION_DELTA': datetime.timedelta(days=7),  # 过期时间
    'JWT_AUTH_HEADER_PREFIX': 'JWT',  # 头部验证前缀 可修改为 Token
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

# 关闭DUBUG 之后会出现资源找不到 运行下列命令
# python3 manage.py collectstatic

STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

# 上传的图片的存储位置
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 默认主题
# SIMPLEUI_DEFAULT_THEME = 'admin.lte.css'
# 修改Logo
# SIMPLEUI_LOGO = 'https://www.baidu.com/img/baidu_resultlogo@2.png'

SIMPLEUI_HOME_INFO = True
# 离线模式 从本地读取所有资源
SIMPLEUI_STATIC_OFFLINE = True
# # 首页标题
# SIMPLEUI_HOME_PAGE = 'https://www.baidu.com'
# SIMPLEUI_HOME_TITLE = '百度一下你就知道'
# SIMPLEUI_HOME_ICON = 'fa fa-user'

# 系统默认分页
# REST_FRAMEWORK = {
#     'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
#     'PAGE_SIZE': 10,
# }


REST_FRAMEWORK = {
    # 'DEFAULT_PERMISSION_CLASSES': (
    # 'rest_framework.permissions.IsAuthenticated',
    # ),
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        # 全局验证
        # 'rest_framework_jwt.authentication.JSONWebTokenAuthentication',  # 这里放到明确的view中就可以明确在哪使用认证
    ],
    # 限速配置
    # 'DEFAULT_THROTTLE_CLASSES': [
    #     # 限速类
    #     'rest_framework.throttling.AnonRateThrottle',  # 用户没有登录的情况
    #     'rest_framework.throttling.UserRateThrottle'  # 用户登录之后的情况
    # ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '50/min',  # 匿名用户
        'user': '100/min'  # 登录之后的用户
    }
}
# 数据导出
IMPORT_EXPORT_USE_TRANSACTIONS = True
# 手机号码正则匹配规则
REGULAR_MOBILE = r'^1[3456789]\d{9}$'

#  linux 中不会隔段时间推出的工具tmux

# 支付宝相关配置
PRIVATE_KEY_PATH = os.path.join(BASE_DIR, 'apps/trade/keys/private_2048.txt')
ALIPAY_KEY_PATH = os.path.join(BASE_DIR, 'apps/trade/keys/alipay_key_2048.txt')
# notify_url 与 return_url
APP_NOTIFY_URL = "http://47.98.34.221:8888/api/alipay/return"
RETURN_URL = "http://47.98.34.221:8888/api/alipay/return"
# 设置缓存过期时间
REST_FRAMEWORK_EXTENSIONS = {
    'DEFAULT_CACHE_RESPONSE_TIMEOUT': 60 * 15
}

# 配置redis缓存
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://:12345@127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# 第三方登录的 KEY 与 SECRET
# 微博
SOCIAL_AUTH_WEIBO_KEY = '501474927'
SOCIAL_AUTH_WEIBO_SECRET = '43e4da02b96d2d258b069cac3163315e'

# 登录成功之后跳转的url
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/index/'

